Calculator/Models/ErrorViewModel.cs
using System;

namespace Calculator.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Calculator/Controllers/CalculatorController.cs
using Microsoft.AspNetCore.Mvc;
using System;

namespace Calculator.Controllers
{
    public class CalculatorController : Controller
    {
        public class CalcModel
        {
            public string Formula { get; set; }
            public string DisplayedNumber { get; set; } = null;
            public double ResultNumber { get; set; } = 0;
            public string Action { get; set; } = null;
            public bool ActionSignControl { get; set; }

        }

        private static readonly CalcModel Calc = new();


        public IActionResult Index()
        {
            return View(Calc);
        }

        public IActionResult SetNumber(string number)
        {
            if (Calc.ActionSignControl)
            {
                Calc.DisplayedNumber = "";
                Calc.ActionSignControl = false;
            }

            Calc.Formula += number;
            Calc.DisplayedNumber += number;


            return RedirectToAction("Index");
        }

        public IActionResult SetFunction(string function)
        {

            switch (function)
            {
                case "clear":
                    {
                        Calc.ResultNumber = 0;
                        Calc.DisplayedNumber = null;
                        Calc.Formula = null;
                        Calc.Action = null;
                        Calc.ActionSignControl = false;
                        break;
                    }

                case "clearLast":
                    {
                        if (Calc.DisplayedNumber != null && Calc.DisplayedNumber.Length > 0 && !Calc.ActionSignControl)
                        {
                            Calc.DisplayedNumber = Calc.DisplayedNumber.Substring(0, Calc.DisplayedNumber.Length - 1);
                            Calc.Formula = Calc.Formula.Substring(0, Calc.Formula.Length - 1);
                        }

                        break;
                    }

                case "equals":
                    {
                        Calculate();
                        Calc.Action = "save";
                        Calc.Formula = Calc.ResultNumber.ToString();
                        Calc.ActionSignControl = false;
                        break;
                    }

                case "changeSign":
                    {
                        if (Calc.DisplayedNumber != null && Calc.DisplayedNumber.Length > 0 && !Calc.ActionSignControl)
                        {
                            Calc.Formula = Calc.Formula.Substring(0, Calc.Formula.Length - Calc.DisplayedNumber.Length);
                            Calc.DisplayedNumber = (-Convert.ToDouble(Calc.DisplayedNumber)).ToString();
                            Calc.Formula += Calc.DisplayedNumber;
                        }
                        break;
                    }

                case "add":
                    {
                        Calculate();
                        Calc.Action = "add";
                        Calc.Formula += "+";
                        Calc.ActionSignControl = true;
                        break;
                    }

                case "substract":
                    {
                        Calculate();
                        Calc.Action = "substract";
                        Calc.Formula += "-";
                        Calc.ActionSignControl = true;
                        break;
                    }


                case "multiply":
                    {
                        Calculate();
                        Calc.Formula += "*";
                        Calc.Action = "multiply";
                        Calc.ActionSignControl = true;
                        break;
                    }

                case "divide":
                    {
                        Calculate();
                        Calc.Formula += "÷";
                        Calc.Action = "divide";
                        Calc.ActionSignControl = true;
                        break;
                    }
                case "percentage":
                    {
                        Calc.DisplayedNumber = (Convert.ToDouble(Calc.ResultNumber) * (Convert.ToDouble(Calc.DisplayedNumber) / 100)).ToString();
                        Calc.Formula += "%";
                        if (Calc.Action != "multiply")
                            Calculate();
                        Calc.Action = "save";
                        break;
                    }
                case "fraction":
                    {
                        if (Calc.DisplayedNumber != null && Calc.DisplayedNumber.Length > 0 && !Calc.ActionSignControl)
                        {
                            Calc.Formula = Calc.Formula.Substring(0, Calc.Formula.Length - Calc.DisplayedNumber.Length);
                            Calc.Formula += "1/" + Calc.DisplayedNumber;
                        }
                        Calc.DisplayedNumber = (1 / Convert.ToDouble(Calc.DisplayedNumber)).ToString();

                        break;
                    }
                case "power":
                    {
                        Calculate();
                        Calc.Formula += "^";
                        Calc.Action = "power";
                        Calc.ActionSignControl = true;
                        break;
                    }
                case "root":
                    {

                        if (Calc.DisplayedNumber != null && Calc.DisplayedNumber.Length > 0 && !Calc.ActionSignControl)
                        {
                            Calc.Formula = Calc.Formula.Substring(0, Calc.Formula.Length - Calc.DisplayedNumber.Length);
                            Calc.Formula += "√" + Calc.DisplayedNumber;
                        }
                        Calc.DisplayedNumber = Math.Sqrt(Convert.ToDouble(Calc.DisplayedNumber)).ToString();
                        break;
                    }

                default:
                    break;
            }



            return RedirectToAction("Index");
        }

        public void Calculate()
        {
            if (Calc.Formula != null && Calc.ActionSignControl && Calc.Formula.Length > 0)
            {
                Calc.Formula = Calc.Formula.Substring(0, Calc.Formula.Length - 1);
            }
            else if (Calc.DisplayedNumber != null && Calc.DisplayedNumber.Length > 0)
            {
                Calc.ActionSignControl = false;
                switch (Calc.Action)
                {
                    case "add":
                        Calc.ResultNumber += Convert.ToDouble(Calc.DisplayedNumber);

                        break;
                    case "substract":
                        Calc.ResultNumber -= Convert.ToDouble(Calc.DisplayedNumber);

                        break;
                    case "multiply":
                        Calc.ResultNumber *= Convert.ToDouble(Calc.DisplayedNumber);

                        break;
                    case "divide":
                        Calc.ResultNumber = Calc.ResultNumber / Convert.ToDouble(Calc.DisplayedNumber);
                        break;


                    case "power":
                        Calc.ResultNumber = Math.Pow(Calc.ResultNumber, Convert.ToDouble(Calc.DisplayedNumber));
                        break;


                    default:
                        Calc.ResultNumber = Convert.ToDouble(Calc.DisplayedNumber);
                        return;
                }
                Calc.DisplayedNumber = Calc.ResultNumber.ToString();
            }
        }
    }
}

Calculator/Controllers/HomeController.cs
using Calculator.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Calculator.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Calculator/Views/Calculator/Index.cshtml
@{
    ViewData["Title"] = "Calc Page";
}
@model Calculator.Controllers.CalculatorController.CalcModel


<div class="flex-grow-1 d-flex pt-4">
    <div class="container text-center calc_body" >
        <div>
            <input class="w-100 font-md text-right" disabled asp-for="Formula" value="@Model?.Formula" />
        </div>
        <div>
            <input type="number"  class="w-100 font-md text-right" asp-for="DisplayedNumber" value="@Model?.DisplayedNumber" />
        </div>
        <div class="calc_row">
            <a asp-route-function="percentage" asp-action="SetFunction" class="btn btn-secondary calc_column ">%</a>
            <a class="btn btn-secondary calc_column">CE</a>
            <a asp-route-function="clear" asp-action="SetFunction" class="btn btn-secondary calc_column">C</a>
            <a asp-route-function="clearLast" asp-action="SetFunction" class="btn btn-secondary calc_column"><span class="iconify" data-icon="feather:delete" data-inline="false"></span></a>
        </div>
        <div class="calc_row">
            <a asp-route-function="fraction" asp-action="SetFunction" class="btn btn-secondary calc_column">1/x</a>
            <a asp-route-function="power" asp-action="SetFunction" class="btn btn-secondary calc_column">x²</a>
            <a asp-route-function="root" asp-action="SetFunction" class="btn btn-secondary calc_column">√x</a>
            <a asp-route-function="divide" asp-action="SetFunction" class="btn btn-secondary calc_column">÷</a>
        </div>
        <div class="calc_row">
            <a  asp-route-number="7" asp-action="SetNumber" class="btn btn-secondary calc_column">7</a>
            <a  asp-route-number="8" asp-action="SetNumber" class="btn btn-secondary calc_column">8</a>
            <a  asp-route-number="9" asp-action="SetNumber" class="btn btn-secondary calc_column">9</a>
            <a  asp-route-function="multiply" asp-action="SetFunction" class=" btn btn-secondary calc_column">*</a>
        </div>
        <div class="calc_row">
            <a asp-route-number="4" asp-action="SetNumber" class="btn btn-secondary calc_column">4</a>
            <a asp-route-number="5" asp-action="SetNumber" class="btn btn-secondary calc_column">5</a>
            <a asp-route-number="6" asp-action="SetNumber" class="btn btn-secondary calc_column" >6</a>
            <a asp-route-function="substract" asp-action="SetFunction" class="btn btn-secondary calc_column">-</a>
        </div>
        <div class="calc_row">
            <a asp-route-number="1" asp-action="SetNumber" class="btn btn-secondary calc_column">1</a>
            <a asp-route-number="2" asp-action="SetNumber" class="btn btn-secondary calc_column">2</a>
            <a asp-route-number="3" asp-action="SetNumber" class="btn btn-secondary calc_column">3</a>
            <a asp-route-function="add" asp-action="SetFunction" class="btn btn-secondary calc_column">+</a>
        </div>
        <div class="calc_row">
            <a asp-route-function="changeSign" asp-action="SetFunction" class="btn btn-secondary calc_column">+/-</a>
            <a asp-route-number="0" asp-action="SetNumber" class="btn btn-secondary calc_column">0</a>
            <a asp-route-number="," asp-action="SetNumber" class="btn btn-secondary calc_column">,</a>
            <a asp-route-function="equals" asp-action="SetFunction" class=" btn btn-secondary calc_column">=</a>
        </div>
    </div>
</div>

Calculator/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center text_white_bold flex-grow-1 d-flex justify-content-center align-items-center">
    <div class="container">
        <h1 class="display-1">Welcome!</h1>
        <p>Want to count your crewmates alive?</p>
        <p>...or maybe how many of them left to kill?</p>
        <a class="text-white font-md" asp-controller="Calculator" asp-action="Index">Try <span class="m-0 text-dark">S</span>US!</a>
    </div>
   
</div>

Calculator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Calculator</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="home_background text_white_bold">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark  box-shadow ">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Calculator" asp-action="Index"><span class="iconify" data-icon="fluent:calculator-20-filled" data-inline="false"  style="width:32px; height:32px"></span>CalcuSUS <img src="/assets/imposter.png" class="imposter" alt="imposter" />  </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link  @(ViewContext.RouteData.Values["Action"].ToString() == "Index" && ViewContext.RouteData.Values["Controller"].ToString() == "Home" ? "active" : "")" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  @(ViewContext.RouteData.Values["Action"].ToString() == "Index" && ViewContext.RouteData.Values["Controller"].ToString() == "Calculator" ? "active" : "")" asp-area="" asp-controller="Calculator" asp-action="Index">Calculator</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <section class="flex-grow-1 d-flex flex-column ">
        @RenderBody()
    </section>


    <footer class="footer">
        <div class="container d-flex align-content-center ">
            <p class="m-0"> &copy; 2021 - Calu - Created by Niria</p>
            <p class="ml-auto m-0 mx-1">Find more:</p>
            <a class="text-white" href="https://github.com/Niiria" target="_blank"> <span class="iconify" data-icon="fa-brands:git-square" style="width:32px; height:32px" data-inline="false"></span></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.iconify.design/1/1.0.7/iconify.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>